;this file for FamiTone2 library generated by text2data tool

FirstSong_music_data:
	.byte 1
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; New song

@instruments:
	.byte $30 ;instrument $00
	.word @env1,@env0,@env0
	.byte $00
	.byte $30 ;instrument $01
	.word @env2,@env0,@env0
	.byte $00
	.byte $30 ;instrument $02
	.word @env3,@env0,@env0
	.byte $00
	.byte $30 ;instrument $03
	.word @env4,@env0,@env0
	.byte $00

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $cc,$03,$c5,$c0,$00,$02
@env2:
	.byte $c5,$c4,$c2,$c2,$c5,$c0,$00,$01
@env3:
	.byte $c6,$04,$c0,$00,$02
@env4:
	.byte $cc,$ca,$c8,$c5,$c2,$c0,$00,$05


; New song
@song0ch0:
	.byte $fb,$06
@song0ch0loop:
@ref0:
	.byte $80,$4b,$53,$55,$5d,$63,$33,$3b,$3c,$81
@ref1:
	.byte $44,$4a,$4e,$48,$4b,$53,$55,$5d,$63,$32,$81
@ref2:
	.byte $3b,$3d,$44,$4e,$4a,$48,$4b,$53,$55,$5c,$81
@ref3:
	.byte $63,$33,$3b,$3d,$44,$85,$6a,$66,$62,$60
	.byte $fd
	.word @song0ch0loop

; New song
@song0ch1:
@song0ch1loop:
@ref4:
	.byte $82,$6a,$9d
@ref5:
	.byte $62,$9d
@ref6:
	.byte $60,$8d,$5c,$8d
@ref7:
	.byte $54,$8d,$52,$8d
	.byte $fd
	.word @song0ch1loop

; New song
@song0ch2:
@song0ch2loop:
@ref8:
	.byte $84,$6a,$85,$62,$85,$5c,$85,$6a,$85
@ref9:
	.byte $62,$85,$5c,$85,$62,$85,$5c,$85
@ref10:
	.byte $54,$85,$62,$85,$5c,$85,$54,$85
@ref11:
	.byte $4e,$85,$5c,$85,$58,$85,$4e,$85
	.byte $fd
	.word @song0ch2loop

; New song
@song0ch3:
@song0ch3loop:
@ref12:
	.byte $86,$08,$85,$08,$85,$08,$85,$08,$83,$08
@ref13:
	.byte $08,$85,$08,$85,$08,$85,$08,$83,$08
	.byte $ff,$09
	.word @ref13
	.byte $ff,$09
	.word @ref13
	.byte $fd
	.word @song0ch3loop

; New song
@song0ch4:
@song0ch4loop:
@ref16:
	.byte $9f
@ref17:
	.byte $9f
@ref18:
	.byte $9f
@ref19:
	.byte $9f
	.byte $fd
	.word @song0ch4loop
