;this file for FamiTone5 library generated by text2vol5 tool
;edited by Doug Fraker, 2019, to add volume column, all notes, 
;duty envelopes, and effects 1xx,2xx,3xx,4xx,Qxx,Rxx


ralph4_music_data:
	.byte 2
	.word @instruments
	.word @samples-3
	.word @song0ch0,@song0ch1,@song0ch2,@song0ch3,@song0ch4,307,256 ; title/end
	.word @song1ch0,@song1ch1,@song1ch2,@song1ch3,@song1ch4,307,256 ; ingame

@instruments:
	.word @env1,@env12,@env0,@env0
	.word @env2,@env13,@env0,@env0
	.word @env3,@env14,@env0,@env0
	.word @env4,@env14,@env0,@env0
	.word @env5,@env0,@env0,@env0
	.word @env6,@env0,@env20,@env22
	.word @env7,@env0,@env0,@env22
	.word @env8,@env0,@env0,@env23
	.word @env9,@env18,@env21,@env23
	.word @env10,@env15,@env0,@env0
	.word @env10,@env16,@env0,@env0
	.word @env10,@env17,@env0,@env0
	.word @env7,@env18,@env0,@env23
	.word @env7,@env0,@env0,@env23
	.word @env11,@env19,@env0,@env0
	.word @env11,@env16,@env0,@env0
	.word @env11,@env17,@env0,@env0

@samples:
@env0:
	.byte $c0,$00,$00
@env1:
	.byte $c0,$cf,$cf,$c3,$c2,$c0,$00,$05
@env2:
	.byte $c0,$cf,$cb,$c9,$c6,$c5,$c5,$c4,$02,$c3,$02,$c2,$02,$c1,$c0,$00
	.byte $0e
@env3:
	.byte $c0,$c6,$c3,$c0,$00,$03
@env4:
	.byte $c0,$c8,$c4,$05,$c3,$05,$c2,$05,$c1,$05,$c0,$00,$0a
@env5:
	.byte $c0,$cf,$00,$01
@env6:
	.byte $c0,$c6,$c9,$c8,$00,$03
@env7:
	.byte $c0,$c2,$00,$01
@env8:
	.byte $c0,$ca,$c7,$c6,$03,$c3,$c1,$c0,$00,$07
@env9:
	.byte $c0,$c9,$cb,$cb,$ca,$c9,$c7,$c5,$c5,$c6,$c7,$c8,$00,$0b
@env10:
	.byte $c0,$ca,$c9,$c7,$c7,$c6,$04,$c4,$02,$c3,$02,$c2,$c1,$00,$0c
@env11:
	.byte $c0,$c6,$06,$c5,$0c,$c4,$0d,$c3,$0c,$c2,$00,$09
@env12:
	.byte $c0,$c3,$c0,$c0,$00,$03
@env13:
	.byte $c0,$c5,$c1,$c0,$c9,$00,$04
@env14:
	.byte $c0,$c0,$c1,$00,$02
@env15:
	.byte $c0,$c0,$c6,$c6,$c3,$c3,$00,$00
@env16:
	.byte $c0,$c0,$c7,$c7,$c4,$c4,$00,$00
@env17:
	.byte $c0,$c0,$c8,$c8,$c3,$c3,$00,$00
@env18:
	.byte $c0,$bd,$bf,$c0,$00,$03
@env19:
	.byte $c0,$c0,$c7,$c7,$c3,$c3,$00,$00
@env20:
	.byte $d4,$ca,$c0,$09,$bf,$be,$bf,$c0,$c1,$c2,$c1,$c0,$00,$04
@env21:
	.byte $c0,$0f,$c1,$c3,$c1,$c0,$bf,$bd,$bf,$c0,$00,$02
@env22:
	.byte $c1,$00,$00
@env23:
	.byte $c2,$c1,$c2,$00,$02


; title/end
@song0ch0:
	.byte $fb,$0c
@song0ch0loop:
@ref0:
	.byte $9e,$22,$8d,$a0,$21,$8d
@ref1:
	.byte $9c,$1f,$9d
@ref2:
	.byte $a0,$1f,$9d
@ref3:
	.byte $9e,$1d,$9d
@ref4:
	.byte $9c,$1f,$8d,$1a,$8d
@ref5:
	.byte $9e,$1b,$9d
@ref6:
	.byte $a0,$1a,$8d,$9c,$1a,$8d
@ref7:
	.byte $9e,$1b,$9d
	.byte $fd
	.word @song0ch0loop

; title/end
@song0ch1:
@song0ch1loop:
@ref8:
	.byte $90,$2e,$83,$35,$98,$2e,$90,$35,$98,$35,$90,$33,$81,$32,$98,$32
	.byte $90,$30,$81,$32,$33,$32
@ref9:
	.byte $81,$30,$2e,$98,$2e,$90,$2e,$30,$32,$2e,$81,$2e,$2d,$2e,$81,$98
	.byte $2e,$2d,$2e
@ref10:
	.byte $90,$33,$2e,$30,$37,$81,$2e,$30,$33,$81,$2e,$30,$37,$81,$35,$33
	.byte $35
@ref11:
	.byte $35,$81,$98,$35,$90,$33,$81,$98,$33,$90,$32,$98,$32,$90,$32,$81
	.byte $33,$30,$85,$98,$30
@ref12:
	.byte $8a,$26,$83,$22,$81,$8c,$22,$8a,$26,$81,$26,$83,$24,$81,$22,$21
	.byte $22
@ref13:
	.byte $26,$83,$1f,$91,$8c,$1f,$8a,$21,$22
@ref14:
	.byte $22,$83,$22,$8c,$22,$8a,$22,$24,$22,$21,$83,$21,$8c,$21,$8a,$22
	.byte $21,$1d
@ref15:
	.byte $1f,$83,$26,$91,$8c,$26,$90,$26,$29
	.byte $fd
	.word @song0ch1loop

; title/end
@song0ch2:
@song0ch2loop:
@ref16:
	.byte $88,$16,$16,$22,$16,$81,$16,$22,$16,$11,$11,$1d,$11,$81,$11,$1d
	.byte $11
@ref17:
	.byte $13,$13,$1f,$13,$81,$13,$1f,$13,$13,$13,$1f,$13,$81,$13,$1f,$13
@ref18:
	.byte $18,$18,$24,$18,$81,$18,$24,$18,$18,$18,$24,$18,$81,$18,$24,$18
@ref19:
	.byte $1d,$1d,$29,$1d,$81,$1d,$29,$1d,$1d,$1d,$29,$1d,$1d,$29,$1d,$29
@ref20:
	.byte $1f,$81,$2b,$1f,$81,$1f,$2b,$1f,$1d,$81,$29,$1d,$81,$1d,$29,$1d
@ref21:
	.byte $1b,$81,$27,$1b,$81,$1b,$27,$1b,$1b,$81,$27,$1b,$81,$1b,$27,$1b
@ref22:
	.byte $16,$81,$22,$16,$81,$16,$22,$16,$1a,$81,$26,$1a,$81,$1a,$26,$1a
	.byte $ff,$10
	.word @ref21
	.byte $fd
	.word @song0ch2loop

; title/end
@song0ch3:
@song0ch3loop:
@ref24:
	.byte $80,$01,$81,$82,$02,$80,$01,$84,$0c,$86,$0c,$82,$02,$80,$01,$01
	.byte $81,$82,$02,$80,$01,$84,$0c,$86,$0c,$82,$02,$80,$01
@ref25:
	.byte $01,$81,$82,$02,$80,$01,$84,$0c,$86,$0c,$82,$02,$80,$01,$01,$81
	.byte $82,$02,$80,$01,$84,$0c,$86,$0c,$82,$02,$80,$01
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref25
	.byte $ff,$10
	.word @ref25
	.byte $fd
	.word @song0ch3loop

; title/end
@song0ch4:
@song0ch4loop:
@ref32:
	.byte $9f
@ref33:
	.byte $9f
@ref34:
	.byte $9f
@ref35:
	.byte $9f
@ref36:
	.byte $9f
@ref37:
	.byte $9f
@ref38:
	.byte $9f
@ref39:
	.byte $9f
	.byte $fd
	.word @song0ch4loop


; ingame
@song1ch0:
	.byte $fb,$0a
@song1ch0loop:
@ref40:
	.byte $83,$92,$23,$81,$94,$1f,$1f,$81,$1f,$83,$92,$23,$81,$94,$1f,$1f
	.byte $83
@ref41:
	.byte $83,$92,$23,$81,$94,$1f,$1f,$81,$1f,$83,$92,$23,$81,$94,$1f,$1f
	.byte $81,$96,$1f
@ref42:
	.byte $83,$1f,$81,$1f,$1f,$81,$21,$83,$21,$81,$21,$21,$83
@ref43:
	.byte $83,$92,$23,$81,$94,$1f,$1f,$81,$1f,$83,$92,$23,$81,$94,$1f,$1f
	.byte $81,$1f
	.byte $ff,$0d
	.word @ref40
	.byte $ff,$0e
	.word @ref41
	.byte $ff,$0d
	.word @ref42
	.byte $ff,$0e
	.word @ref43
@ref48:
	.byte $00,$81,$98,$2e,$85,$32,$83,$30,$87,$2e,$30
@ref49:
	.byte $2e,$30,$33,$81,$33,$35,$37,$33,$81,$35,$81,$30,$81,$2d,$81,$2e
@ref50:
	.byte $30,$32,$2e,$81,$2e,$81,$30,$32,$81,$30,$81,$30,$81,$30,$32,$33
@ref51:
	.byte $35,$33,$37,$81,$37,$35,$81,$37,$81,$39,$81,$39,$37,$35,$30,$81
@ref52:
	.byte $96,$23,$83,$23,$83,$23,$81,$21,$21,$81,$21,$81,$21,$83
@ref53:
	.byte $23,$83,$23,$83,$23,$83,$21,$83,$21,$85
@ref54:
	.byte $23,$83,$23,$83,$23,$81,$21,$21,$81,$21,$81,$21,$83
@ref55:
	.byte $1f,$83,$1f,$83,$1f,$83,$21,$83,$21,$85
	.byte $ff,$0d
	.word @ref54
	.byte $ff,$0a
	.word @ref53
	.byte $ff,$0a
	.word @ref55
@ref59:
	.byte $23,$83,$23,$83,$23,$83,$23,$23,$81,$23,$23,$83
	.byte $fd
	.word @song1ch0loop

; ingame
@song1ch1:
@song1ch1loop:
@ref60:
	.byte $83,$8a,$29,$8c,$29,$8a,$28,$29,$8c,$28,$8a,$26,$81,$26,$24,$23
	.byte $87
@ref61:
	.byte $8c,$23,$81,$8a,$29,$8c,$29,$8a,$28,$29,$8c,$28,$8a,$2f,$81,$2f
	.byte $2d,$2b,$81,$2f,$2d,$2b
@ref62:
	.byte $2b,$83,$27,$83,$2b,$81,$2d,$83,$29,$81,$26,$29,$2b
@ref63:
	.byte $2b,$2b,$29,$2b,$8c,$29,$8a,$2b,$81,$8c,$2b,$8a,$2b,$8e,$32,$2f
	.byte $2b,$2f,$2b,$26,$23
@ref64:
	.byte $9a,$23,$8a,$23,$29,$8c,$29,$8a,$28,$29,$8c,$28,$8a,$26,$81,$26
	.byte $24,$23,$87
@ref65:
	.byte $8c,$23,$8a,$29,$2f,$8c,$29,$8a,$2d,$2f,$8c,$2d,$8a,$30,$81,$2f
	.byte $2d,$2f,$81,$2f,$2d,$2f
@ref66:
	.byte $2b,$83,$2e,$83,$33,$81,$30,$83,$2e,$81,$2d,$2b,$2d
@ref67:
	.byte $2f,$2f,$8c,$2f,$8a,$2f,$8c,$2f,$8a,$2b,$2d,$2f,$81,$8e,$2f,$32
	.byte $2f,$37,$32,$2f,$2b
@ref68:
	.byte $90,$2e,$85,$32,$83,$30,$87,$2e,$30,$2e,$30
@ref69:
	.byte $33,$81,$33,$35,$37,$33,$81,$35,$81,$30,$81,$2d,$81,$2e,$30,$32
@ref70:
	.byte $2e,$81,$2e,$81,$30,$32,$81,$30,$81,$30,$81,$30,$32,$33,$35,$33
@ref71:
	.byte $37,$81,$37,$35,$81,$37,$81,$39,$81,$39,$37,$35,$30,$81,$35,$81
@ref72:
	.byte $37,$37,$98,$37,$90,$32,$37,$3b,$98,$3b,$90,$39,$98,$39,$90,$35
	.byte $98,$35,$90,$30,$35,$81,$30,$81
@ref73:
	.byte $2f,$81,$98,$2f,$90,$32,$98,$32,$90,$2f,$98,$32,$90,$30,$8b,$98
	.byte $30,$81
@ref74:
	.byte $90,$2f,$2b,$2f,$32,$98,$32,$90,$37,$98,$32,$90,$35,$81,$34,$98
	.byte $35,$90,$32,$98,$34,$90,$30,$81,$98,$30
@ref75:
	.byte $90,$2e,$98,$2e,$90,$2e,$2e,$98,$2e,$90,$2e,$98,$2e,$90,$30,$98
	.byte $30,$90,$35,$98,$30,$90,$39,$98,$35,$90,$3c,$81,$98,$3c
@ref76:
	.byte $90,$3b,$3b,$98,$3b,$90,$37,$3b,$3e,$98,$3e,$90,$3c,$98,$3e,$90
	.byte $3b,$98,$3c,$90,$3b,$39,$81,$37,$81
@ref77:
	.byte $37,$81,$98,$37,$90,$32,$37,$3b,$37,$39,$8b,$98,$39,$81
@ref78:
	.byte $90,$37,$81,$33,$37,$81,$3a,$81,$39,$81,$3a,$81,$3c,$81,$3e,$83
@ref79:
	.byte $3b,$3c,$3b,$37,$81,$39,$81,$37,$8d,$98,$37
	.byte $fd
	.word @song1ch1loop

; ingame
@song1ch2:
@song1ch2loop:
@ref80:
	.byte $88,$1f,$1f,$00,$18,$1a,$1d,$00,$1f,$00,$1f,$00,$1f,$18,$1a,$1d
	.byte $1a
@ref81:
	.byte $1f,$1f,$00,$18,$1a,$1d,$00,$1f,$00,$1f,$00,$1f,$18,$1a,$1d,$1a
@ref82:
	.byte $1b,$1b,$00,$1b,$22,$1b,$00,$1d,$81,$1d,$18,$1d,$00,$18,$1a,$1d
	.byte $ff,$10
	.word @ref81
	.byte $ff,$10
	.word @ref81
	.byte $ff,$10
	.word @ref81
	.byte $ff,$10
	.word @ref82
	.byte $ff,$10
	.word @ref81
	.byte $ff,$10
	.word @ref82
	.byte $ff,$10
	.word @ref82
	.byte $ff,$10
	.word @ref82
	.byte $ff,$10
	.word @ref82
	.byte $ff,$10
	.word @ref81
	.byte $ff,$10
	.word @ref81
	.byte $ff,$10
	.word @ref81
@ref95:
	.byte $1b,$1b,$00,$16,$1b,$1b,$00,$1d,$00,$1d,$00,$16,$18,$1a,$1d,$1a
	.byte $ff,$10
	.word @ref81
	.byte $ff,$10
	.word @ref81
	.byte $ff,$10
	.word @ref95
	.byte $ff,$10
	.word @ref81
	.byte $fd
	.word @song1ch2loop

; ingame
@song1ch3:
@song1ch3loop:
@ref100:
	.byte $80,$01,$84,$0c,$82,$02,$80,$01,$01,$84,$0c,$82,$02,$86,$0c,$80
	.byte $01,$84,$0c,$82,$02,$80,$01,$01,$84,$0c,$82,$02,$86,$0c
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref100
@ref103:
	.byte $80,$01,$84,$0c,$82,$02,$80,$01,$01,$84,$0c,$82,$02,$86,$0c,$80
	.byte $01,$84,$0c,$82,$02,$02,$80,$01,$82,$02,$86,$0c,$82,$02
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref103
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref100
	.byte $ff,$10
	.word @ref100
@ref119:
	.byte $80,$01,$84,$0c,$82,$02,$80,$01,$01,$84,$0c,$82,$02,$02,$80,$01
	.byte $82,$02,$02,$02,$80,$01,$82,$02,$02,$02
	.byte $fd
	.word @song1ch3loop

; ingame
@song1ch4:
@song1ch4loop:
@ref120:
	.byte $9f
@ref121:
	.byte $9f
@ref122:
	.byte $9f
@ref123:
	.byte $9f
@ref124:
	.byte $9f
@ref125:
	.byte $9f
@ref126:
	.byte $9f
@ref127:
	.byte $9f
@ref128:
	.byte $9f
@ref129:
	.byte $9f
@ref130:
	.byte $9f
@ref131:
	.byte $9f
@ref132:
	.byte $9f
@ref133:
	.byte $9f
@ref134:
	.byte $9f
@ref135:
	.byte $9f
@ref136:
	.byte $9f
@ref137:
	.byte $9f
@ref138:
	.byte $9f
@ref139:
	.byte $9f
	.byte $fd
	.word @song1ch4loop
